server:
  port: 8070

spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/jt_db
        username: root
        password: root
 

mybatis:
  typeAliasesPackage: cn.tedu.ssm.pojo
  mapperLocations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true  #开器驼峰命名

logging:
  level: 
    cn.tedu.ssm.mapper: debug
    
    
